In [10]:
import numpy as np

myarr = np.array([[1,2,3],[34,56,34]])

In [11]:
print(myarr[0,1])

2


In [12]:
listarr = np.array([[1,2,4],[3,4,5]])
print(listarr[0,2])


print(listarr.shape)
print(listarr.size)
print(listarr.dtype)


4
(2, 3)
6
int64


In [13]:
zeros = np.zeros((2,5)) # will initailize the array with 0
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
ones = np.ones((2,5)) # will intialize the array with 1
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
rarr= np.arange(15) # will initialize the array with n-1 intergers from 0
print(rarr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
lspace = np.linspace(1,50,10) # (first-ele,last-ele,no of ele)
# linspace will equally distibute 10 numbers in between 1 and 50
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp_like = np.empty_like(myarr) # this will create an empty array of similar construction with myarr
# then  any element can be inserted to that array

print(emp_like)

[[0 1 0]
 [0 0 0]]


In [22]:
ide = np.identity(10) # this will create an indentity matrix of order 10
ide

ide.shape

(10, 10)

In [26]:
arr = np.arange(10)
print(arr)

new_arr= arr.reshape(2,5)  # NOTE : (num1,num2)  num1*num2 must the no of element in the previous array
new_arr

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
new_arr = new_arr.ravel()  # this will convert the 2d array to 1d array
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Axis

In [32]:

# we can assume a point in cartessian coordiante system, for x-y plane to locate any point we need 
#  two axis, axis in numpy is same as cartessian axis
# axis=0  for 1D array
# axis =1 for 2D array

# axis=0 is along rows
# axis=1 is along columns

ar = np.array([[1,2,3],[3,45,67],[11,12,13]])

print(ar)

ar.sum(axis=0) # this will add all elements in a column along the rows
ar.sum(axis=1) # this will add all elements in a row along the columns
# first line ar.sum(axis=0) will not show up after writing ar.sum(axis=1)

[[ 1  2  3]
 [ 3 45 67]
 [11 12 13]]
[15 59 83]


array([  6, 115,  36])

In [34]:
ar.T  #  this will transpose the original matrix

array([[ 1,  3, 11],
       [ 2, 45, 12],
       [ 3, 67, 13]])

In [36]:
ar.flat  # this will give an iterator

for item in ar.flat: # the iterator will traverse through the array and print all elements
    print(item)


1
2
3
3
45
67
11
12
13


In [37]:
ar.ndim  # shows the no of dimensions in the given array


2

In [38]:
ar.size  # shows total numbers of elements in the array


9

In [39]:
ar.shape  # shows the construction of array

(3, 3)

In [40]:
ar.nbytes # this will give no of bytes conserved

72

In [41]:
ar.argmax() # gives the index where maximum element is present

5

In [42]:
ar.argmin() # gives the index where minimum element is present

0

In [43]:
ar.argsort() # gives an array of indices of the elements on increasing order of elements

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [45]:
ar.argmax(axis=0)  # if we assume a matrix ar, so in column1 max value at index 2
# column2 max value at index 1
# column3 max value at index 1


array([2, 1, 1])

In [47]:
ar.argmin(axis=0)

array([0, 0, 0])